name: Build and Upload Docker Image

on:
  push:
    branches:
      - main  # 更改为你的默认分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        export IMAGE_TAG="nextselfbuild:2.18.5"
        docker build -t $IMAGE_TAG .
    
    - name: Check if file already exists
      run: |
        if [ -f "nextselfbuild.tar.gz" ]; then
          echo "nextselfbuild.tar.gz already exists, deleting it..."
          rm nextselfbuild.tar.gz
        else
          echo "No existing nextselfbuild.tar.gz found."
        fi

    - name: Save Docker image to a tar file
      run: |
        export IMAGE_TAG="nextselfbuild:2.18.5"
        docker save $IMAGE_TAG | gzip > nextselfbuild.tar.gz

    - name: Upload to Tencent Cloud COS
      env:
        COS_BUCKET_NAME: ${{ secrets.COS_BUCKET_NAME }}
        COS_REGION: ${{ secrets.COS_REGION }}
        COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
      run: |
        pip install -U cos-python-sdk-v5
        python upload2cos.py