name: Build and Upload Docker Image

on:
  push:
    branches:
      - main  # 更改为你的默认分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Create an empty tar file
      run: |
        # 创建一个空的 tar.gz 文件
        touch nextselfbuild.tar.gz

    - name: Upload to Tencent Cloud COS
      env:
        COS_BUCKET_NAME: ${{ secrets.COS_BUCKET_NAME }}
        COS_REGION: ${{ secrets.COS_REGION }}
        COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
      run: |
        pip install -U cos-python-sdk-v5
        python upload2cos.py