name: Build and Upload Docker Image

on:
  push:
    branches:
      - main  # 更改为你的默认分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        export IMAGE_TAG="nextselfbuild:2.18.5.$(date +%Y%m%d%H%M)"
        docker build -t $IMAGE_TAG .

    - name: Save Docker image to a tar file
      run: |
        export IMAGE_TAG="nextselfbuild:2.18.5.$(date +%Y%m%d%H%M)"
        docker save $IMAGE_TAG | gzip > nextselfbuild.tar.gz

    - name: Upload to Tencent Cloud COS
      env:
        COS_BUCKET_NAME: ${{ secrets.COS_BUCKET_NAME }}
        COS_REGION: ${{ secrets.COS_REGION }}
        COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
      run: |
        pip install cos-python-sdk-v5
        python -c |
          import os
          from qcloud_cos import CosConfig, CosS3Client

          # 初始化配置信息
          config = CosConfig(
              Region=os.getenv('COS_REGION'),
              SecretId=os.getenv('COS_SECRET_ID'),
              SecretKey=os.getenv('COS_SECRET_KEY'),
              Scheme='https'
          )
          client = CosS3Client(config)

          # 上传文件到 COS
          response = client.put_object_from_local_file(
              Bucket=os.getenv('COS_BUCKET_NAME'),
              LocalFilePath='nextselfbuild.tar.gz',
              Key='nextselfbuild.tar.gz'
          )
          print('Upload completed:', response['ETag'])
